package info.jab.eulerproblems.eulerproblem2;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Test suite for Euler Problem 2.
 * 
 * Problem statement: 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 */
@DisplayName("Euler Problem 2 Tests")
class EulerProblem2Test {

    private EulerProblem2 solution = new EulerProblem2();

    @Test
    @DisplayName("Should return correct sum of even Fibonacci numbers below 4 million")
    void shouldReturnSumOfEvenFibonacciNumbersBelowFourMillion() {
        // Given
        long limit = 4_000_000L;
        long expected = 4613732L;

        // When
        long result = solution.sumEvenFibonacciBelow(limit);

        // Then
        assertThat(result).isEqualTo(expected);
    }

    @Test
    @DisplayName("Should return 2 for limit 10 (only 2 and 8 are even and below 10)")
    void shouldReturnCorrectSumForSmallLimit() {
        // Given
        // Fibonacci sequence: 1, 2, 3, 5, 8, 13, ...
        // Even values below 10: 2, 8
        // Sum: 2 + 8 = 10
        long limit = 10L;
        long expected = 10L;

        // When
        long result = solution.sumEvenFibonacciBelow(limit);

        // Then
        assertThat(result).isEqualTo(expected);
    }

    @Test
    @DisplayName("Should return 0 for limit below first even Fibonacci number")
    void shouldReturnZeroForLimitBelowFirstEvenFibonacci() {
        // Given
        long limit = 1L;
        long expected = 0L;

        // When
        long result = solution.sumEvenFibonacciBelow(limit);

        // Then
        assertThat(result).isEqualTo(expected);
    }
}
