package info.jab.eulerproblems.eulerproblem2;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.*;

/**
 * Test suite for Euler Problem 2: Even Fibonacci Numbers.
 * 
 * Problem statement:
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
@DisplayName("Euler Problem 2: Even Fibonacci Numbers")
class EulerProblem2Test {

    private final EulerProblem2 solution = new EulerProblem2();

    @Test
    @DisplayName("Should calculate sum of even Fibonacci terms up to 4,000,000")
    void shouldCalculateSumOfEvenFibonacciTermsUpToFourMillion() {
        // Given
        long maxValue = 4_000_000L;

        // When
        long result = solution.sumOfEvenFibonacciTerms(maxValue);

        // Then
        assertThat(result).isEqualTo(4_613_732L);
    }

    @Test
    @DisplayName("Should calculate sum of even Fibonacci terms up to 100")
    void shouldCalculateSumOfEvenFibonacciTermsUpToHundred() {
        // Given
        // Fibonacci sequence up to 100: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
        // Even terms: 2, 8, 34
        // Sum: 2 + 8 + 34 = 44
        long maxValue = 100L;

        // When
        long result = solution.sumOfEvenFibonacciTerms(maxValue);

        // Then
        assertThat(result).isEqualTo(44L);
    }

    @Test
    @DisplayName("Should calculate sum of even Fibonacci terms up to 10")
    void shouldCalculateSumOfEvenFibonacciTermsUpToTen() {
        // Given
        // Fibonacci sequence up to 10: 1, 2, 3, 5, 8
        // Even terms: 2, 8
        // Sum: 2 + 8 = 10
        long maxValue = 10L;

        // When
        long result = solution.sumOfEvenFibonacciTerms(maxValue);

        // Then
        assertThat(result).isEqualTo(10L);
    }

    @Test
    @DisplayName("Should return 0 for max value less than 2")
    void shouldReturnZeroForMaxValueLessThanTwo() {
        // Given
        long maxValue = 1L;

        // When
        long result = solution.sumOfEvenFibonacciTerms(maxValue);

        // Then
        assertThat(result).isEqualTo(0L);
    }
}