package info.jab.euler.problems.euler_problem2;

/**
 * Solver for Project Euler problem 2.
 * <p>
 * Problem statement:
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 * </p>
 */
public class EulerProblem2 {

    /**
     * Calculates the sum of even-valued Fibonacci numbers whose values do not exceed the provided limit.
     *
     * @param limit maximum value for Fibonacci numbers considered in the sum
     * @return the sum of even Fibonacci numbers up to the limit
     */
    public long sumOfEvenFibonacciNumbers(long limit) {
        if (limit < 2) {
            return 0L;
        }

        long sum = 0L;
        long previous = 1L;
        long current = 2L;

        while (current <= limit) {
            if ((current & 1L) == 0) {
                sum += current;
            }

            long next = previous + current;
            previous = current;
            current = next;
        }

        return sum;
    }
}
