package info.jab.eulerproblems.eulerproblem2;

/**
 * Solution for Euler Problem 2.
 * 
 * Problem statement: 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 */
public class EulerProblem2 {

    /**
     * Calculates the sum of all even Fibonacci numbers below the given limit.
     * 
     * The Fibonacci sequence starts with 1, 2, 3, 5, 8, 13, 21, 34, ...
     * This method sums only the even-valued terms that are below the limit.
     * 
     * @param limit the upper bound (exclusive) for Fibonacci numbers to consider
     * @return the sum of even Fibonacci numbers below the limit
     */
    public long sumEvenFibonacciBelow(long limit) {
        if (limit <= 2) {
            return 0;
        }

        long sum = 0;
        long first = 1;
        long second = 2;

        // Add 2 if it's below the limit (it's the first even number)
        if (second < limit) {
            sum += second;
        }

        // Generate Fibonacci sequence and sum even numbers
        while (true) {
            long next = first + second;
            
            // Stop if we exceed the limit
            if (next >= limit) {
                break;
            }

            // Add even numbers to the sum
            if (next % 2 == 0) {
                sum += next;
            }

            // Move to next pair
            first = second;
            second = next;
        }

        return sum;
    }
}
