package info.jab.eulerproblems.eulerproblem2;

/**
 * Solution for Euler Problem 2: Even Fibonacci Numbers.
 * 
 * Problem statement:
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 * 
 * Solution approach:
 * We generate Fibonacci numbers iteratively and sum only the even-valued terms
 * until we reach the maximum value threshold.
 */
public class EulerProblem2 {

    /**
     * Calculates the sum of even-valued terms in the Fibonacci sequence
     * whose values do not exceed the specified maximum value.
     * 
     * The Fibonacci sequence starts with 1 and 2.
     * 
     * @param maxValue the maximum value that Fibonacci terms should not exceed
     * @return the sum of even-valued Fibonacci terms
     */
    public long sumOfEvenFibonacciTerms(long maxValue) {
        if (maxValue < 2) {
            return 0;
        }

        long sum = 0;
        long first = 1;
        long second = 2;

        // Include 2 (the first even term) if it doesn't exceed maxValue
        if (second <= maxValue) {
            sum += second;
        }

        // Generate Fibonacci sequence and sum even terms
        while (second <= maxValue) {
            long next = first + second;
            
            // Stop if next term exceeds maxValue
            if (next > maxValue) {
                break;
            }
            
            // Add even terms to the sum
            if (next % 2 == 0) {
                sum += next;
            }
            
            // Move to next pair
            first = second;
            second = next;
        }

        return sum;
    }
}