package info.jab.eulerproblems.eulerproblem2;

/**
 * Solution to Project Euler Problem 2.
 * 
 * Problem: Each new term in the Fibonacci sequence is generated by adding 
 * the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms.
 */
public class EulerProblem2 {

    /**
     * Calculates the sum of even-valued Fibonacci terms that do not exceed the given limit.
     * 
     * The Fibonacci sequence starts with 1, 2, and each subsequent term is the sum 
     * of the previous two terms.
     * 
     * @param limit the maximum value that Fibonacci terms should not exceed
     * @return the sum of all even-valued Fibonacci terms not exceeding the limit
     */
    public long solve(long limit) {
        if (limit < 2) {
            return 0;
        }

        long sum = 0;
        long first = 1;
        long second = 2;

        // Process the sequence and sum even terms
        while (second <= limit) {
            // If the current term is even, add it to the sum
            if (second % 2 == 0) {
                sum += second;
            }

            // Calculate next Fibonacci term
            long next = first + second;
            first = second;
            second = next;
        }

        return sum;
    }
}